### ISSUE TITLE
Add contributing steps

### ISSUE THREAD

**Issue by chavarera** [Python-World/GitProfile#3]
Add contributing steps and guidelines

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.

**Comment by chavarera** [comment]
Sure @ampsteric

**Comment by ampsteric** [comment]
By contributing steps you mean the steps a contributor should follow in order to contribute to this project of yours?

**Comment by ampsteric** [comment]
And can I send the PR on 1st October for the count in Hacktoberfest? or Should I make PR before 1st and you merge it during hacktoberfest?

**Comment by AdityaJ7** [comment]
make it on 1st October or after to be considered under Hacktoberfest

**Comment by ampsteric** [comment]
okay will do that.

**Comment by ampsteric** [comment]
We welcome contributions from everyone. Here are the guidelines if you are thinking of helping us:

Contributions should be made in the form of GitHub pull requests. Each pull request will be reviewed by someone with permission to land patches and either landed in the main tree or given feedback for changes that would be required. All contributions should follow this format.

Should you wish to work on an issue, please claim it first by commenting on the GitHub issue that you want to work on it. This is to prevent duplicated efforts from contributors on the same issue.

Look for good first issues to find good tasks to start with.
Your contributions are always welcome and appreciated. Following are the things you can do to contribute to this project.

Report a bug

If you think you have encountered a new issue, and I should know about it, feel free to report it and I will take care of it.

Create a pull request

It cannot get better then this, your pull request will be appreciated by the community. You can get started by picking up any open issues and make a pull request.

If you are new to open-source, make sure to check read more about it here and learn more about creating a pull request here.

🌵: Branches
No other permanent branches should be created in the main repository, you can create feature branches but they should get merged with the master.

**Comment by ampsteric** [comment]
do you want anything else to be added?

**Comment by AdityaJ7** [comment]
> do you want anything else to be added?

Looks good to me, @chavarera will have the final say

**Comment by ampsteric** [comment]
@chavarera I am waiting for your response.
hope you reply soon..

**Comment by chavarera** [comment]
great @ampsteric 
please add Contributing.md file with steps and guidelines as you mentioned

**Comment by ampsteric** [comment]
okay. Will surely do that by tomorrow.
